name: publish-to-github-pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build (static export)
        run: npm run build

      - name: Disable Jekyll
        run: printf "" > ./out/.nojekyll

      - name: Verify artifact
        run: |
          test -f out/.nojekyll || (echo "::error::.nojekyll missing" && exit 1)
          test -d out/_next || (echo "::error::/_next missing; check basePath/assetPrefix" && exit 1)

      - uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
